### ISSUE TITLE
Server Sent Events don't appear to be working from tengam.org

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/photo-wall-server#2]
1. Open the app https://mozilla-magnet.github.io/photo-wall-client/
2. Upload an image from https://mozilla-magnet.github.io/photo-wall-upload-client/
3. Notice the `EventSource` callback doesn't fire

**Comment by wilsonpage** [comment]
@samgiles do we need to enable something in nginx?

**Comment by samgiles** [comment]
Should be fixed now, just needed to prevent nginx from closing the connection and pass it through properly.
